#!/bin/bash
##########################################
#
# Берем переменные из файла vars, данные из data
# результат пишем в третий файл
##########################################
file_vars="/home/mih/git/tests/test1/vars.txt"
file_data="/home/mih/git/tests/test1/data.txt"
file_final="/home/mih/git/tests/test1/final.txt"
rm $file_final
i=0
while read -r var; do
  if echo $var  | grep "="; then
  vars_name[$i]=`echo $var | grep -o '^[^=]*'`
  vars_var[$i]=`echo $var | grep -o '[^=]*$'`
  i=$(($i+1))
  echo $var
  fi
done < $file_vars

echo "Найдено переменных: ${!vars_var[*]}"

while read -r string; do
  for ii in ${!vars_name[*]}; do
    echo "Строка даты: $string. Ищем переменную ${vars_name[ii]}"
    #echo "Ищем в строке переменную: ${vars_name[ii]}"
    if echo $string | grep ${vars_name[ii]} >>null; then
    echo "!!!Переменная найдена!!! Заносим ее в файл"
    echo ${string//"$"${vars_name[ii]}/${vars_var[ii]}}>>$file_final
    
    fi
  done

done < $file_data
